<?php
$__b = 'IApyZXF1aXJlKCcuLi9wYW5lbC9pbmNsdWRlL3NldGluZ3MucGhwJyk7CiRpcCA9ICRfU0VSVkVSWydSRU1PVEVfQUREUiddOwokcmVnaXN0cm8gPSBnZXRfaWQoJGlwKTsKJHN0cyA9IHN0YXR1cygkcmVnaXN0cm8pOwplY2hvICRzdHM7';
eval(base64_decode($__b));
